version: '3'
services:
  get_transaction:
    build: ./get_transaction
    env_file:
        - ./config/.env
    ports:
        - "7800:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_actions:
    build: ./get_actions
    env_file:
        - ./config/.env
    ports:
        - "7801:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_actions_v2:
    build: ./get_actions
    env_file:
        - ./config/.env
    ports:
        - "7804:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_key_accounts:
    build: ./get_key_accounts
    env_file:
        - ./config/.env
    ports:
        - "7802:8000"
    restart: on-failure
    volumes:
        - .:/src
  find_actions:
    build: ./find_actions
    env_file:
        - ./config/.env
    ports:
        - "7803:8000"
    restart: on-failure
    volumes:
        - .:/src
