version: '3'
services:
  get_transaction:
    build: ./get_transaction
    env_file:
        - ./config/.env
    ports:
        - "8800:8000"
    restart: on-failure
    volumes:
        - .:/src
  get_actions:
    build: ./get_actions
    env_file:
        - ./config/.env
    ports:
        - "8890:8000"
    restart: on-failure
    volumes:
        - .:/src
